version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  # Lambda-specific binary (bootstrap)
  - id: lambda
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -tags=lambda.norpc
      - -trimpath
    ldflags:
      - -X main.buildVersion={{.Version}}
      - -X main.buildCommit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}
      - -s -w
      - -extldflags "-static"
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: "bootstrap"

archives:
  - id: lambda
    builds:
      - lambda
    formats: ["zip"]
    name_template: "{{ .ProjectName }}_lambda_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

snapshot:
  version_template: "{{ .Tag }}-next"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
release:
  draft: false
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .ProjectName }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^build:"

  # Group commits into categories based on their message
  # This is useful for generating a changelog that highlights features, bug fixes, etc.
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Security"
      regexp: "^.*sec[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999
