# https://ko.build/configuration/
baseImage: public.ecr.aws/lambda/provided:al2023

defaultPlatforms:
  - linux/arm64
  - linux/amd64

# AWS Lambda container images require the executable to be named 'bootstrap'
builds:
  - id: apigateway
    dir: .
    main: ./cmd/apigateway/main.go
    binary: bootstrap
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    ldflags:
      - -extldflags "-static"
      - -s -w
      - -X github.com/boogy/aws-oidc-warden/pkg/version.Version={{.Git.Tag}}
      - -X github.com/boogy/aws-oidc-warden/pkg/version.Commit={{.Git.ShortCommit}}
      - -X github.com/boogy/aws-oidc-warden/pkg/version.Date={{.Date}}
    flags:
      - -tags=lambda.norpc
      - -trimpath

  - id: alb
    dir: .
    main: ./cmd/alb/main.go
    binary: bootstrap
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    ldflags:
      - -extldflags "-static"
      - -s -w
      - -X github.com/boogy/aws-oidc-warden/pkg/version.Version={{.Git.Tag}}
      - -X github.com/boogy/aws-oidc-warden/pkg/version.Commit={{.Git.ShortCommit}}
      - -X github.com/boogy/aws-oidc-warden/pkg/version.Date={{.Date}}
    flags:
      - -tags=lambda.norpc
      - -trimpath

  - id: lambdaurl
    dir: .
    main: ./cmd/lambdaurl/main.go
    binary: bootstrap
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    ldflags:
      - -extldflags "-static"
      - -s -w
      - -X github.com/boogy/aws-oidc-warden/pkg/version.Version={{.Git.Tag}}
      - -X github.com/boogy/aws-oidc-warden/pkg/version.Commit={{.Git.ShortCommit}}
      - -X github.com/boogy/aws-oidc-warden/pkg/version.Date={{.Date}}
    flags:
      - -tags=lambda.norpc
      - -trimpath

labels:
  org.opencontainers.image.title: "AWS OIDC Warden"
  org.opencontainers.image.version: "{{.Git.Tag}}"
  org.opencontainers.image.revision: "{{.Git.ShortCommit}}"
  org.opencontainers.image.created: "{{.Date}}"
  org.opencontainers.image.description: "AWS OIDC token validator for GitHub Actions"
  org.opencontainers.image.source: "https://github.com/boogy/aws-oidc-warden"
  org.opencontainers.image.licenses: "Apache License 2.0"
  io.buildpacks.build.metadata: '{"aws_lambda_function_handler": "bootstrap"}'
